# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsdproxy" do
  version "2.0.0"

  on_macos do
    on_intel do
      sha256 "37e275936d97e6cf8d0a354a62ff06f5955a5a6c0acf2c132eef1a72468a504d"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
    on_arm do
      sha256 "173ffb0fd0fdf1d0ed3e18fa6ab8b9e954106e6871182a7ddf8a8f46060add1e"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
  end

  on_linux do
    on_intel do
      sha256 "03c983a289f57ac9f34c8cc1cf61684522385ec913ec70b93d6196b1b28d0c6f"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
    on_arm do
      sha256 "99f28df1b659b01e0c3e6a26f4082966e7b855c36cdd0192e870fed35a3c20d2"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
  end

  name "tsdproxy"
  desc "Tailscale Docker reverse proxy — expose containers with one label"
  homepage "https://github.com/almeidapaulopt/tsdproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsdproxyd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsdproxyd"]
    end
  end

  # No zap stanza required

end
