# This file was generated by GoReleaser. DO NOT EDIT.
cask "tsdproxy" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "9e20b4175ae0127279618568f99ea9d2f861a925f95ef14a352fe596ded77fc2"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
    on_arm do
      sha256 "5e7567c5acf933491ed28745dc0336f75b34714f240bd3af84734e18c3ef55ff"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c34a229c722f7001cb3e36feb50e60fab03193dc3d3ba1236620c8afa51f54c"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
    on_arm do
      sha256 "54e885e9b7b3d9f4dd50f35bc0d7ba69080cd3c95e9fd14a636256def6f23653"
      url "https://github.com/almeidapaulopt/tsdproxy/releases/download/v#{version}/tsdproxy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/almeidapaulopt/tsdproxy/"
    end
  end

  name "tsdproxy"
  desc "Tailscale Docker reverse proxy — expose containers with one label"
  homepage "https://github.com/almeidapaulopt/tsdproxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tsdproxyd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tsdproxyd"]
    end
  end

  # No zap stanza required

end
